In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment is ready!")

Environment is ready!

In [2]:
df = pd.read_csv("../data/raw/samsung_phones.csv")

In [3]:
df.head()

,model_name,series,launch_year,price_inr,ram_gb,storage_gb,processor_score,camera_mp,battery_mah,charging_w,refresh_rate_hz,screen_size_inch,weight_g,ai_features,waterproof,target_segment
0,Galaxy A06,A,2025,10999,4,64,3.5,50,5000,25,60,6.7,189,No,No,budget
1,Galaxy A15 5G,A,2024,17999,6,128,5.0,50,5000,25,90,6.5,200,No,No,budget
2,Galaxy A16 5G,A,2025,19999,8,128,5.5,50,5000,25,90,6.7,198,Basic AI,No,budget
3,Galaxy A25 5G,A,2024,24999,8,128,6.2,50,5000,25,120,6.5,197,Basic AI,No,budget
4,Galaxy A26 5G,A,2025,27999,8,256,6.5,50,5000,25,120,6.7,197,Basic AI,Yes,business

In [4]:
df.describe()

,launch_year,price_inr,ram_gb,storage_gb,processor_score,camera_mp,battery_mah,charging_w,refresh_rate_hz,screen_size_inch,weight_g
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,2024.566667,56132.333333,9.333333,262.400000,7.843333,65.000000,4940.000000,32.666667,112.000000,6.653333,203.566667
std,0.504007,42266.586896,2.940013,128.385626,1.796104,45.769286,653.821657,10.400044,17.498768,0.234496,21.191546
min,2024.000000,10999.000000,4.000000,64.000000,3.500000,50.000000,3900.000000,15.000000,60.000000,6.200000,163.000000
25%,2024.000000,27249.000000,8.000000,160.000000,6.625000,50.000000,4550.000000,25.000000,120.000000,6.600000,189.250000
50%,2025.000000,36999.000000,8.000000,256.000000,7.900000,50.000000,5000.000000,25.000000,120.000000,6.700000,202.500000
75%,2025.000000,82499.000000,12.000000,256.000000,9.650000,50.000000,5000.000000,45.000000,120.000000,6.700000,217.750000
max,2025.000000,169999.000000,16.000000,512.000000,10.000000,200.000000,6500.000000,45.000000,120.000000,7.600000,240.000000